"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.NOTIFICATION_THROTTLE_RULE = exports.NOTIFICATION_THROTTLE_NO_ACTIONS = exports.NOTIFICATION_SUPPORTED_ACTION_TYPES_IDS = exports.MINIMUM_ML_LICENSE = exports.UNAUTHENTICATED_USER = exports.DETECTION_ENGINE_QUERY_SIGNALS_URL = exports.DETECTION_ENGINE_SIGNALS_STATUS_URL = exports.DETECTION_ENGINE_SIGNALS_URL = exports.SIGNALS_INDEX_KEY = exports.TIMELINE_IMPORT_URL = exports.TIMELINE_EXPORT_URL = exports.TIMELINE_URL = exports.DETECTION_ENGINE_PREPACKAGED_RULES_STATUS_URL = exports.DETECTION_ENGINE_RULES_STATUS_URL = exports.DETECTION_ENGINE_TAGS_URL = exports.DETECTION_ENGINE_INDEX_URL = exports.DETECTION_ENGINE_PRIVILEGES_URL = exports.DETECTION_ENGINE_PREPACKAGED_URL = exports.DETECTION_ENGINE_RULES_URL = exports.DETECTION_ENGINE_URL = exports.INTERNAL_IMMUTABLE_KEY = exports.INTERNAL_RULE_ALERT_ID_KEY = exports.INTERNAL_RULE_ID_KEY = exports.INTERNAL_IDENTIFIER = exports.NOTIFICATIONS_ID = exports.SIGNALS_ID = exports.IP_REPUTATION_LINKS_SETTING_DEFAULT = exports.IP_REPUTATION_LINKS_SETTING = exports.NEWS_FEED_URL_SETTING_DEFAULT = exports.NEWS_FEED_URL_SETTING = exports.ENABLE_NEWS_FEED_SETTING = exports.DEFAULT_TIMEPICKER_QUICK_RANGES = exports.DEFAULT_INTERVAL_VALUE = exports.DEFAULT_INTERVAL_TYPE = exports.DEFAULT_INTERVAL_PAUSE = exports.DEFAULT_TO = exports.DEFAULT_FROM = exports.DEFAULT_SCALE_DATE_FORMAT = exports.DEFAULT_MAX_TABLE_QUERY_SIZE = exports.DEFAULT_ANOMALY_SCORE = exports.DEFAULT_SEARCH_AFTER_PAGE_SIZE = exports.DEFAULT_MAX_SIGNALS = exports.DEFAULT_SIGNALS_INDEX = exports.DEFAULT_SIEM_REFRESH_INTERVAL = exports.DEFAULT_SIEM_TIME_RANGE = exports.DEFAULT_REFRESH_RATE_INTERVAL = exports.DEFAULT_TIME_RANGE = exports.DEFAULT_NUMBER_FORMAT = exports.DEFAULT_INDEX_KEY = exports.DEFAULT_DARK_MODE = exports.DEFAULT_DATE_FORMAT_TZ = exports.DEFAULT_DATE_FORMAT = exports.DEFAULT_BYTES_FORMAT = exports.APP_NAME = exports.APP_ID = void 0;

/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License;
 * you may not use this file except in compliance with the Elastic License.
 */
const APP_ID = 'siem';
exports.APP_ID = APP_ID;
const APP_NAME = 'SIEM';
exports.APP_NAME = APP_NAME;
const DEFAULT_BYTES_FORMAT = 'format:bytes:defaultPattern';
exports.DEFAULT_BYTES_FORMAT = DEFAULT_BYTES_FORMAT;
const DEFAULT_DATE_FORMAT = 'dateFormat';
exports.DEFAULT_DATE_FORMAT = DEFAULT_DATE_FORMAT;
const DEFAULT_DATE_FORMAT_TZ = 'dateFormat:tz';
exports.DEFAULT_DATE_FORMAT_TZ = DEFAULT_DATE_FORMAT_TZ;
const DEFAULT_DARK_MODE = 'theme:darkMode';
exports.DEFAULT_DARK_MODE = DEFAULT_DARK_MODE;
const DEFAULT_INDEX_KEY = 'siem:defaultIndex';
exports.DEFAULT_INDEX_KEY = DEFAULT_INDEX_KEY;
const DEFAULT_NUMBER_FORMAT = 'format:number:defaultPattern';
exports.DEFAULT_NUMBER_FORMAT = DEFAULT_NUMBER_FORMAT;
const DEFAULT_TIME_RANGE = 'timepicker:timeDefaults';
exports.DEFAULT_TIME_RANGE = DEFAULT_TIME_RANGE;
const DEFAULT_REFRESH_RATE_INTERVAL = 'timepicker:refreshIntervalDefaults';
exports.DEFAULT_REFRESH_RATE_INTERVAL = DEFAULT_REFRESH_RATE_INTERVAL;
const DEFAULT_SIEM_TIME_RANGE = 'siem:timeDefaults';
exports.DEFAULT_SIEM_TIME_RANGE = DEFAULT_SIEM_TIME_RANGE;
const DEFAULT_SIEM_REFRESH_INTERVAL = 'siem:refreshIntervalDefaults';
exports.DEFAULT_SIEM_REFRESH_INTERVAL = DEFAULT_SIEM_REFRESH_INTERVAL;
const DEFAULT_SIGNALS_INDEX = '.siem-signals';
exports.DEFAULT_SIGNALS_INDEX = DEFAULT_SIGNALS_INDEX;
const DEFAULT_MAX_SIGNALS = 100;
exports.DEFAULT_MAX_SIGNALS = DEFAULT_MAX_SIGNALS;
const DEFAULT_SEARCH_AFTER_PAGE_SIZE = 100;
exports.DEFAULT_SEARCH_AFTER_PAGE_SIZE = DEFAULT_SEARCH_AFTER_PAGE_SIZE;
const DEFAULT_ANOMALY_SCORE = 'siem:defaultAnomalyScore';
exports.DEFAULT_ANOMALY_SCORE = DEFAULT_ANOMALY_SCORE;
const DEFAULT_MAX_TABLE_QUERY_SIZE = 10000;
exports.DEFAULT_MAX_TABLE_QUERY_SIZE = DEFAULT_MAX_TABLE_QUERY_SIZE;
const DEFAULT_SCALE_DATE_FORMAT = 'dateFormat:scaled';
exports.DEFAULT_SCALE_DATE_FORMAT = DEFAULT_SCALE_DATE_FORMAT;
const DEFAULT_FROM = 'now-24h';
exports.DEFAULT_FROM = DEFAULT_FROM;
const DEFAULT_TO = 'now';
exports.DEFAULT_TO = DEFAULT_TO;
const DEFAULT_INTERVAL_PAUSE = true;
exports.DEFAULT_INTERVAL_PAUSE = DEFAULT_INTERVAL_PAUSE;
const DEFAULT_INTERVAL_TYPE = 'manual';
exports.DEFAULT_INTERVAL_TYPE = DEFAULT_INTERVAL_TYPE;
const DEFAULT_INTERVAL_VALUE = 300000; // ms

exports.DEFAULT_INTERVAL_VALUE = DEFAULT_INTERVAL_VALUE;
const DEFAULT_TIMEPICKER_QUICK_RANGES = 'timepicker:quickRanges';
/** This Kibana Advanced Setting enables the `Security news` feed widget */

exports.DEFAULT_TIMEPICKER_QUICK_RANGES = DEFAULT_TIMEPICKER_QUICK_RANGES;
const ENABLE_NEWS_FEED_SETTING = 'siem:enableNewsFeed';
/** This Kibana Advanced Setting specifies the URL of the News feed widget */

exports.ENABLE_NEWS_FEED_SETTING = ENABLE_NEWS_FEED_SETTING;
const NEWS_FEED_URL_SETTING = 'siem:newsFeedUrl';
/** The default value for News feed widget */

exports.NEWS_FEED_URL_SETTING = NEWS_FEED_URL_SETTING;
const NEWS_FEED_URL_SETTING_DEFAULT = 'https://feeds.elastic.co/security-solution';
/** This Kibana Advanced Setting specifies the URLs of `IP Reputation Links`*/

exports.NEWS_FEED_URL_SETTING_DEFAULT = NEWS_FEED_URL_SETTING_DEFAULT;
const IP_REPUTATION_LINKS_SETTING = 'siem:ipReputationLinks';
/** The default value for `IP Reputation Links` */

exports.IP_REPUTATION_LINKS_SETTING = IP_REPUTATION_LINKS_SETTING;
const IP_REPUTATION_LINKS_SETTING_DEFAULT = `[
  { "name": "virustotal.com", "url_template": "https://www.virustotal.com/gui/search/{{ip}}" },
  { "name": "talosIntelligence.com", "url_template": "https://talosintelligence.com/reputation_center/lookup?search={{ip}}" }
]`;
/**
 * Id for the signals alerting type
 */

exports.IP_REPUTATION_LINKS_SETTING_DEFAULT = IP_REPUTATION_LINKS_SETTING_DEFAULT;
const SIGNALS_ID = `${APP_ID}.signals`;
/**
 * Id for the notifications alerting type
 */

exports.SIGNALS_ID = SIGNALS_ID;
const NOTIFICATIONS_ID = `${APP_ID}.notifications`;
/**
 * Special internal structure for tags for signals. This is used
 * to filter out tags that have internal structures within them.
 */

exports.NOTIFICATIONS_ID = NOTIFICATIONS_ID;
const INTERNAL_IDENTIFIER = '__internal';
exports.INTERNAL_IDENTIFIER = INTERNAL_IDENTIFIER;
const INTERNAL_RULE_ID_KEY = `${INTERNAL_IDENTIFIER}_rule_id`;
exports.INTERNAL_RULE_ID_KEY = INTERNAL_RULE_ID_KEY;
const INTERNAL_RULE_ALERT_ID_KEY = `${INTERNAL_IDENTIFIER}_rule_alert_id`;
exports.INTERNAL_RULE_ALERT_ID_KEY = INTERNAL_RULE_ALERT_ID_KEY;
const INTERNAL_IMMUTABLE_KEY = `${INTERNAL_IDENTIFIER}_immutable`;
/**
 * Detection engine routes
 */

exports.INTERNAL_IMMUTABLE_KEY = INTERNAL_IMMUTABLE_KEY;
const DETECTION_ENGINE_URL = '/api/detection_engine';
exports.DETECTION_ENGINE_URL = DETECTION_ENGINE_URL;
const DETECTION_ENGINE_RULES_URL = `${DETECTION_ENGINE_URL}/rules`;
exports.DETECTION_ENGINE_RULES_URL = DETECTION_ENGINE_RULES_URL;
const DETECTION_ENGINE_PREPACKAGED_URL = `${DETECTION_ENGINE_RULES_URL}/prepackaged`;
exports.DETECTION_ENGINE_PREPACKAGED_URL = DETECTION_ENGINE_PREPACKAGED_URL;
const DETECTION_ENGINE_PRIVILEGES_URL = `${DETECTION_ENGINE_URL}/privileges`;
exports.DETECTION_ENGINE_PRIVILEGES_URL = DETECTION_ENGINE_PRIVILEGES_URL;
const DETECTION_ENGINE_INDEX_URL = `${DETECTION_ENGINE_URL}/index`;
exports.DETECTION_ENGINE_INDEX_URL = DETECTION_ENGINE_INDEX_URL;
const DETECTION_ENGINE_TAGS_URL = `${DETECTION_ENGINE_URL}/tags`;
exports.DETECTION_ENGINE_TAGS_URL = DETECTION_ENGINE_TAGS_URL;
const DETECTION_ENGINE_RULES_STATUS_URL = `${DETECTION_ENGINE_RULES_URL}/_find_statuses`;
exports.DETECTION_ENGINE_RULES_STATUS_URL = DETECTION_ENGINE_RULES_STATUS_URL;
const DETECTION_ENGINE_PREPACKAGED_RULES_STATUS_URL = `${DETECTION_ENGINE_RULES_URL}/prepackaged/_status`;
exports.DETECTION_ENGINE_PREPACKAGED_RULES_STATUS_URL = DETECTION_ENGINE_PREPACKAGED_RULES_STATUS_URL;
const TIMELINE_URL = '/api/timeline';
exports.TIMELINE_URL = TIMELINE_URL;
const TIMELINE_EXPORT_URL = `${TIMELINE_URL}/_export`;
exports.TIMELINE_EXPORT_URL = TIMELINE_EXPORT_URL;
const TIMELINE_IMPORT_URL = `${TIMELINE_URL}/_import`;
/**
 * Default signals index key for kibana.dev.yml
 */

exports.TIMELINE_IMPORT_URL = TIMELINE_IMPORT_URL;
const SIGNALS_INDEX_KEY = 'signalsIndex';
exports.SIGNALS_INDEX_KEY = SIGNALS_INDEX_KEY;
const DETECTION_ENGINE_SIGNALS_URL = `${DETECTION_ENGINE_URL}/signals`;
exports.DETECTION_ENGINE_SIGNALS_URL = DETECTION_ENGINE_SIGNALS_URL;
const DETECTION_ENGINE_SIGNALS_STATUS_URL = `${DETECTION_ENGINE_SIGNALS_URL}/status`;
exports.DETECTION_ENGINE_SIGNALS_STATUS_URL = DETECTION_ENGINE_SIGNALS_STATUS_URL;
const DETECTION_ENGINE_QUERY_SIGNALS_URL = `${DETECTION_ENGINE_SIGNALS_URL}/search`;
/**
 * Common naming convention for an unauthenticated user
 */

exports.DETECTION_ENGINE_QUERY_SIGNALS_URL = DETECTION_ENGINE_QUERY_SIGNALS_URL;
const UNAUTHENTICATED_USER = 'Unauthenticated';
/*
  Licensing requirements
 */

exports.UNAUTHENTICATED_USER = UNAUTHENTICATED_USER;
const MINIMUM_ML_LICENSE = 'platinum';
/*
  Rule notifications options
*/

exports.MINIMUM_ML_LICENSE = MINIMUM_ML_LICENSE;
const NOTIFICATION_SUPPORTED_ACTION_TYPES_IDS = ['.email', '.slack', '.pagerduty', '.webhook'];
exports.NOTIFICATION_SUPPORTED_ACTION_TYPES_IDS = NOTIFICATION_SUPPORTED_ACTION_TYPES_IDS;
const NOTIFICATION_THROTTLE_NO_ACTIONS = 'no_actions';
exports.NOTIFICATION_THROTTLE_NO_ACTIONS = NOTIFICATION_THROTTLE_NO_ACTIONS;
const NOTIFICATION_THROTTLE_RULE = 'rule';
exports.NOTIFICATION_THROTTLE_RULE = NOTIFICATION_THROTTLE_RULE;